<script setup>
import { ref } from "vue";
import { PhCheckCircle, PhCloudArrowDown, PhKey, PhPlus, PhQuestion, PhWarning } from "@phosphor-icons/vue";
import { useAlertSources } from "../composables/useAlertSources";
import AlertSourceDialog from "./AlertSourceDialog.vue";
const createOpen = ref(false);
const { sources, selectedId, detail, receipts, listState, detailState, error, operationState, operationError, retryableOperation, oneTimeToken, loadList, loadDetail, selectSource, submitCreate, submitUpdate, rotateCredential, revokeCredential, retryLastOperation, clearOneTimeToken } = useAlertSources();
async function create(command) { if (await submitCreate(command)) createOpen.value = false; }
function toggleSource() { if (!detail.value) return; submitUpdate({ expected_version: detail.value.version, state: detail.value.enabled ? "DISABLED" : "ENABLED" }); }
</script>
<template><div data-testid="alert-source-center" class="source-manager-page">
  <header class="source-page-header"><div><h2>接入源管理</h2><p>管理真实告警入口、凭据和最近接收结果</p></div><button data-testid="create-source" type="button" class="button primary" @click="createOpen = true"><PhPlus :size="16" />新增告警源</button></header>
  <div class="source-workspace"><section class="source-list-panel"><div v-if="listState === 'loading'" class="empty-state"><PhCloudArrowDown :size="24" /><strong>正在读取告警源</strong></div><div v-else-if="listState === 'error'" class="empty-state error-state"><PhQuestion :size="24" /><strong>{{ error }}</strong><button class="button secondary" @click="loadList">重新加载</button></div><div v-else-if="listState === 'empty'" class="empty-state"><PhCheckCircle :size="24" /><strong>尚未配置告警源</strong></div><button v-for="source in sources" v-else :key="source.id" type="button" :class="['source-list-item', { selected: source.id === selectedId }]" @click="selectSource(source.id)"><span><strong>{{ source.name }}</strong><span :class="['source-health', source.receiveState === '已收到数据' ? 'healthy' : 'waiting']">{{ source.receiveState }}</span></span><small>{{ source.type }} · {{ source.management }}</small><small>最近收到：{{ source.lastReceivedAt }}</small></button></section>
  <section class="source-detail-panel"><div v-if="detailState === 'loading'" class="detail-placeholder"><PhCloudArrowDown :size="28" /><strong>正在读取来源详情</strong></div><div v-else-if="detailState === 'error'" class="detail-placeholder error-state"><PhQuestion :size="28" /><strong>{{ error }}</strong><button class="button secondary" @click="loadDetail(selectedId)">重试</button></div><div v-else-if="!detail" class="detail-placeholder"><PhCloudArrowDown :size="28" /><strong>选择告警源后查看详情</strong></div><template v-else><header class="source-detail-header"><div><div class="detail-title-line"><h2>{{ detail.name }}</h2><span class="badge badge-active">{{ detail.state }}</span><span class="badge badge-medium">{{ detail.management }}</span></div><p>{{ detail.type }} · {{ detail.receiveState }}</p></div><div v-if="detail.editable" class="detail-actions"><button class="button secondary" :disabled="operationState === 'pending'" @click="toggleSource">{{ detail.enabled ? "停用来源" : "启用来源" }}</button><button class="button primary" :disabled="operationState === 'pending'" @click="rotateCredential"><PhKey :size="16" />轮换凭据</button></div></header>
    <div v-if="operationError" class="operation-error-banner"><div><PhWarning :size="18" />{{ operationError }}</div><button v-if="retryableOperation" class="button secondary" @click="retryLastOperation">使用原操作重试</button><button v-else-if="operationState === 'conflict'" class="button secondary" @click="loadList(selectedId)">刷新来源</button></div>
    <div class="source-detail-body"><section class="source-endpoint-card"><h3>专属 Webhook 地址</h3><code>{{ detail.webhookPath }}</code><p>数据发送方使用当前来源的有效 Token 进行认证。</p></section><section class="source-counts"><article><span>接收成功</span><strong>{{ detail.acceptedRequests }}</strong></article><article><span>接收失败</span><strong>{{ detail.rejectedRequests }}</strong></article><article><span>新建告警</span><strong>{{ detail.counts.opened }}</strong></article><article><span>更新告警</span><strong>{{ detail.counts.updated }}</strong></article></section>
      <section class="source-section"><h3>凭据</h3><div v-if="!detail.credentials.length" class="compact-empty">暂无可展示凭据</div><div v-for="credential in detail.credentials" :key="credential.id" class="credential-row"><div><strong>{{ credential.id }}</strong><span>{{ credential.state }} · 创建于 {{ credential.createdAt }} · 最近使用 {{ credential.lastUsedAt }}</span></div><button v-if="detail.editable && credential.active" class="button secondary" :disabled="operationState === 'pending'" @click="revokeCredential(credential.id)">撤销</button></div></section>
      <section class="source-section"><h3>最近接收记录</h3><div v-if="!receipts.length" class="compact-empty">最近 30 天尚无接收记录</div><div v-for="receipt in receipts" :key="receipt.id" class="receipt-row"><span :class="['receipt-outcome', receipt.tone]">{{ receipt.outcome }}</span><strong>{{ receipt.receivedAt }}</strong><span>输入 {{ receipt.inputCount }} · 新建 {{ receipt.opened }} · 更新 {{ receipt.updated }} · 恢复 {{ receipt.resolved }}</span></div></section>
    </div></template></section></div>
  <AlertSourceDialog :open="createOpen" :disabled="operationState === 'pending'" @close="createOpen = false" @submit="create" />
  <div v-if="oneTimeToken" class="dialog-backdrop"><section class="operation-dialog token-dialog"><header><div><span>只显示这一次</span><h3>请立即保存接入 Token</h3></div></header><p>关闭后平台无法再次展示；如果丢失，需要轮换新凭据。</p><code>{{ oneTimeToken }}</code><footer><button data-testid="confirm-token-saved" type="button" class="button primary" @click="clearOneTimeToken">我已安全保存</button></footer></section></div>
</div></template>
