from enum import StrEnum


class AlertState(StrEnum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"


class AlertGroupState(StrEnum):
    FORMING = "FORMING"
    ACTIVE = "ACTIVE"
    OBSERVING = "OBSERVING"
    CLOSED = "CLOSED"


class AlertGroupMembershipState(StrEnum):
    AUTO_CONFIRMED = "AUTO_CONFIRMED"
    MANUAL_CONFIRMED = "MANUAL_CONFIRMED"
    PENDING = "PENDING"
    REMOVED = "REMOVED"


class StormState(StrEnum):
    NORMAL = "NORMAL"
    STORM = "STORM"


class IncidentState(StrEnum):
    DETECTED = "DETECTED"
    TRIAGING = "TRIAGING"
    INVESTIGATING = "INVESTIGATING"
    MITIGATING = "MITIGATING"
    MONITORING_RECOVERY = "MONITORING_RECOVERY"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class DiagnosisState(StrEnum):
    QUEUED = "QUEUED"
    COLLECTING = "COLLECTING"
    NORMALIZING = "NORMALIZING"
    SNAPSHOT_READY = "SNAPSHOT_READY"
    ANALYZING = "ANALYZING"
    REPORT_READY = "REPORT_READY"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class CatalogState(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class DependencyState(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class CorrelationJobState(StrEnum):
    PENDING = "PENDING"
    LEASED = "LEASED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class CorrelationOutcome(StrEnum):
    SKIPPED_SERVICE_MISSING = "SKIPPED_SERVICE_MISSING"
    CREATED_NO_MATCH = "CREATED_NO_MATCH"
    LINKED_EXACT_SERVICE = "LINKED_EXACT_SERVICE"
    LINKED_EXISTING = "LINKED_EXISTING"
    CREATED_AMBIGUOUS = "CREATED_AMBIGUOUS"
    CREATED_DEPENDENCY_CANDIDATE = "CREATED_DEPENDENCY_CANDIDATE"
    REJECTED_INELIGIBLE = "REJECTED_INELIGIBLE"
    RECORDED_RESOLUTION = "RECORDED_RESOLUTION"
    SUPERSEDED = "SUPERSEDED"


class LinkRelation(StrEnum):
    PRIMARY = "PRIMARY"
    RELATED = "RELATED"
