from enum import StrEnum


class AlertState(StrEnum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    SUPPRESSED = "SUPPRESSED"


class IncidentState(StrEnum):
    DETECTED = "DETECTED"
    TRIAGING = "TRIAGING"
    INVESTIGATING = "INVESTIGATING"
    MITIGATING = "MITIGATING"
    MONITORING_RECOVERY = "MONITORING_RECOVERY"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class DiagnosisState(StrEnum):
    QUEUED = "QUEUED"
    COLLECTING = "COLLECTING"
    NORMALIZING = "NORMALIZING"
    SNAPSHOT_READY = "SNAPSHOT_READY"
    ANALYZING = "ANALYZING"
    REPORT_READY = "REPORT_READY"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
